languageCode = "en"
languageName = "English"
weight = 1
title = "Amber Atac"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Amber Atac"
  image = "img/amber.jpeg"
  headline = "I'm only human"
  bio = "A loving girlfriend"
  links = [
    { email = "mailto:hello@your_domain.com" },
    { github = "https://github.com/username" },
    { instagram = "https://instagram.com/username" },
    { linkedin = "https://linkedin.com/in/username" },
    { pinterest = "https://pinterest.com/username" },
    { twitter = "https://twitter.com/username" },
  ]
